import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Loader2, Copy, Linkedin, BookOpen, MessageSquare, Video, PenLine, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { venusService, BrandingContent } from "@/services/venusService";

const CONTENT_TYPES = [
  { key: "linkedin_post", label: "LinkedIn Post", icon: MessageSquare, desc: "Thought leadership, 150–300 words" },
  { key: "thought_leadership", label: "Article", icon: BookOpen, desc: "Long-form, 600–1200 words" },
  { key: "video_script", label: "Video Script", icon: Video, desc: "2–4 min talking points" },
  { key: "board_bio", label: "Board Bio", icon: PenLine, desc: "50–80 word exec bio" },
] as const;
type ContentType = typeof CONTENT_TYPES[number]["key"];

const DEMO_CONTENT: Record<ContentType, (topic: string) => string> = {
  linkedin_post: (topic) => `🚀 A hard truth about ${topic || "scaling startups"}:\n\nWhen I was building my first company, I thought the biggest risk was running out of money.\n\nI was wrong.\n\nThe real risk? Moving too slowly once you have conviction.\n\nHere's what I've learned from 3 exits:\n\n1. Speed compounds. A decision made in 2 hours beats a perfect decision made in 2 weeks.\n\n2. Data is a lag indicator. By the time the metrics confirm your thesis, competitors are 6 months ahead.\n\n3. Your best operators want to move fast. Slow decision-making is your #1 retention risk.\n\nWhat's your biggest lesson from scaling a team?\n\n#Leadership #Startups #ExecLife\n\n— Generated by Venus AI Executive Career OS`,
  thought_leadership: (topic) => `# ${topic || "The Future of Executive Leadership"}\n\nIn the next five years, the definition of executive leadership will be rewritten.\n\nThe forces reshaping it — AI, remote-first teams, distributed capital — are not coming. They are here. And the executives who thrive will be those who understand this isn't a change in tools. It's a change in leverage.\n\n## Why Old Playbooks Break\n\nThe traditional executive playbook was built for a world of information scarcity and geographic proximity. Both are gone.\n\nToday's executive must operate differently:\n- **Decision velocity** over decision perfection\n- **Async-first communication** over presence theater\n- **Network as infrastructure** over network as social capital\n\n## The New Executive Stack\n\nThe most effective C-suite leaders I know have rebuilt their operating system around three pillars...\n\n[Full article continues — connect Venus API for complete Groq-generated content]\n\n— Generated by Venus AI Executive Career OS`,
  video_script: (topic) => `[INTRO — 0:00–0:20]\n"${topic || "What got me here won't get me to the next level"} — and after 3 exits, I finally understand why."\n\n[HOOK — 0:20–0:45]\nPause for effect. "The moment I stopped being a builder and started being a multiplier — that's when everything changed."\n\n[POINT 1 — 0:45–1:30]\nTalk about the first transition: IC → manager. What breaks. What you have to let go of.\n\n[POINT 2 — 1:30–2:15]\nThe second transition: manager → executive. The shift from outputs to outcomes. Give a specific example.\n\n[POINT 3 — 2:15–3:00]\nThe third transition: executive → board/fractional. Why most execs miss it. The leverage unlock.\n\n[CTA — 3:00–3:30]\n"If this resonates, follow me — I share one insight per week from the operator's seat."\n\n— Generated by Venus AI Executive Career OS`,
  board_bio: (topic) => `Senior executive with 15+ years building and scaling technology companies. ${topic ? `Focused on ${topic}.` : ""} Former CTO of two venture-backed companies (combined $1.6B in exits). Board experience across SaaS, fintech, and B2B marketplace verticals. Deep expertise in engineering org design, AI/ML infrastructure, and enterprise go-to-market. Current focus: advising Series B–D companies navigating the AI transition.\n\n— Generated by Venus AI Executive Career OS`,
};

function ContentCard({ content, onCopy, onPublish }: {
  content: BrandingContent;
  onCopy: () => void;
  onPublish: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(content.content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      onCopy();
    });
  };
  return (
    <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl border border-gray-200 bg-white p-5 space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-black uppercase tracking-widest bg-blue-100 text-blue-700 mr-2">
            {content.content_type.replace("_", " ")}
          </span>
          {content.topic && <span className="text-xs text-gray-400">· {content.topic}</span>}
        </div>
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={handleCopy}
            className="h-7 text-xs border-gray-300 text-gray-500 hover:bg-gray-100">
            {copied ? <CheckCircle className="h-3 w-3 mr-1 text-emerald-600" /> : <Copy className="h-3 w-3 mr-1" />}
            {copied ? "Copied!" : "Copy"}
          </Button>
          {content.content_type === "linkedin_post" && (
            <Button size="sm" onClick={onPublish}
              className="h-7 text-xs bg-[#0A66C2] hover:bg-[#0A66C2]/90 text-white">
              <Linkedin className="h-3 w-3 mr-1" /> Open LinkedIn
            </Button>
          )}
        </div>
      </div>
      <div className="rounded-xl border border-gray-200 bg-gray-50 p-4 max-h-72 overflow-y-auto">
        <pre className="text-sm text-gray-600 whitespace-pre-wrap font-sans leading-relaxed">{content.content}</pre>
      </div>
    </motion.div>
  );
}

export default function ExecutiveBranding() {
  const [contentType, setContentType] = useState<ContentType>("linkedin_post");
  const [topic, setTopic] = useState("");
  const [generating, setGenerating] = useState(false);
  const [library, setLibrary] = useState<BrandingContent[]>([]);

  const generate = async () => {
    setGenerating(true);
    try {
      const content = await venusService.generateBrandingContent({ content_type: contentType, topic });
      setLibrary(l => [content, ...l]);
      toast.success("Content generated.");
    } catch {
      toast.error("API not connected — showing demo content.");
      const demo: BrandingContent = {
        id: `local-${Date.now()}`,
        content_type: contentType,
        topic: topic || undefined,
        content: DEMO_CONTENT[contentType](topic),
        created_at: new Date().toISOString(),
      };
      setLibrary(l => [demo, ...l]);
    } finally {
      setGenerating(false);
    }
  };

  const publish = (content: BrandingContent) => {
    navigator.clipboard.writeText(content.content).then(() => {
      toast.success("Copied to clipboard — opening LinkedIn to paste.");
      window.open("https://www.linkedin.com/feed/", "_blank", "noopener");
    }).catch(() => {
      toast.error("Could not copy. Select the text manually and paste on LinkedIn.");
      window.open("https://www.linkedin.com/feed/", "_blank", "noopener");
    });
  };

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      <div>
        <p className="text-[10px] font-bold uppercase tracking-widest text-blue-600">Phase 3 · Resume & Brand</p>
        <h1 className="text-2xl font-black text-gray-900 mt-0.5">Executive Branding</h1>
        <p className="text-sm text-gray-400 mt-1">AI-generated thought leadership content powered by Groq.</p>
      </div>

      {/* Generator */}
      <div className="rounded-2xl border border-gray-200 bg-white p-5 space-y-4">
        <p className="text-xs font-black uppercase tracking-widest text-gray-500">Content Type</p>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
          {CONTENT_TYPES.map(ct => {
            const Icon = ct.icon;
            return (
              <button key={ct.key} type="button" onClick={() => setContentType(ct.key)}
                className={`rounded-xl border p-3 text-left transition-all ${contentType === ct.key ? "border-blue-400 bg-blue-50" : "border-gray-200 bg-gray-50 hover:border-gray-300"}`}>
                <Icon className={`h-5 w-5 mb-1.5 ${contentType === ct.key ? "text-blue-600" : "text-gray-400"}`} />
                <p className="text-xs font-bold text-gray-900">{ct.label}</p>
                <p className="text-[10px] text-gray-400 mt-0.5">{ct.desc}</p>
              </button>
            );
          })}
        </div>

        <div>
          <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500 mb-1.5 block">
            Topic / Thesis (optional)
          </label>
          <Input value={topic} onChange={e => setTopic(e.target.value)}
            placeholder="e.g. AI is changing how executives make decisions"
            className="bg-gray-100 border-gray-300 text-gray-900 placeholder:text-gray-400 rounded-xl" />
        </div>

        <Button onClick={generate} disabled={generating}
          className="w-full bg-blue-600 hover:bg-blue-700 text-white h-11">
          {generating
            ? <><Loader2 className="h-4 w-4 animate-spin mr-2" />Generating with Groq AI...</>
            : <><Sparkles className="h-4 w-4 mr-2" />Generate Content</>}
        </Button>
      </div>

      {/* Content library */}
      {library.length > 0 && (
        <div className="space-y-4">
          <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Content Library ({library.length})</p>
          <AnimatePresence>
            {library.map((c, i) => (
              <ContentCard key={c.id || i} content={c}
                onCopy={() => toast.success("Copied to clipboard.")}
                onPublish={() => publish(c)} />
            ))}
          </AnimatePresence>
        </div>
      )}

      {library.length === 0 && !generating && (
        <div className="rounded-2xl border border-dashed border-gray-200 py-16 text-center">
          <PenLine className="h-10 w-10 text-gray-300 mx-auto mb-3" />
          <p className="text-gray-400 font-semibold">Select content type and generate</p>
          <p className="text-xs text-gray-400 mt-1">Groq AI creates executive-quality content in under 5 seconds</p>
        </div>
      )}
    </div>
  );
}
